apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web
    version: '2'
  name: nginx
  namespace: theo-examen
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - image: nginx
          name: nginx-theo
          ports:
            - containerPort: 80
