apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx
  namespace: theo-examen

spec:
  ingressClassName: nginx
  rules:
    - host: app-theo.ludovic.tech
      http:
        paths:
          - backend:
            service:
              name: nginx
              port:
                number: 80
            path: /
            pathType: Prefix
