apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: www-data
  namespace: theo-examen
spec:
  storageClassName: nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Mi
